Set `allow_broken_conditionals` configuration variable at `ansible.cfg`. (#9634)
Currently, CI is breaking with:

```
Wednesday 10 September 2025  14:27:33 +0000 (0:00:00.273)       0:16:18.634 *** 
Error: : Task failed: Conditional result (True) was derived from value of type 'str' at "<CLI option '-e'>". Conditionals must have a boolean result.
```

This is likely because the installed `ansible` is now on version
`2.19.2`. The error is documented
[here](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_core_2.19.html#example-implicit-boolean-conversion).
~In order to quickly fix it, I have introduced
`ALLOW_BROKEN_CONDITIONALS=1` environment variable before
`ansible-playbook` executions.~

**Key Changes:**

- Add `allow_broken_conditionals = true` to ansible configuration file
`ansible.cfg`