benchmarks/aggregate: fix in-place map (#6136)
This somehow worked when generating CSV, but matplotlib fails with
    RuntimeError: matplotlib does not support generators as input
Fix it.